eureka:
  instance:
    homePageUrl: https://${eureka.instance.hostName}/
    home-page-url-path: https://${eureka.instance.hostName}
  client:
    serviceUrl:
      defaultZone: https://n5-subprj-eurekaserver.herokuapp.com/
